/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestparc.vue;

import gestparc.controleur.Controleur;
import gestparc.modele.InterventionCarrosserie;
import gestparc.modele.InterventionMecanique;
import gestparc.modele.Vehicule;
import gestparc.modele.enums.PieceCarrosserie;
import gestparc.modele.enums.PieceMecanique;
import gestparc.modele.enums.TypeCarrosserie;
import gestparc.modele.enums.TypeMecanique;
import javax.swing.DefaultComboBoxModel;

/**
 * Fenêtre d'ajout d'une nouvelle intervention à un véhicule.
 * @author vpivet
 */
public class AjoutInterventionVue extends javax.swing.JFrame {
    private Controleur ctrl;
    private Vehicule v;
    /**
     * Creates new form AjoutInterventionVue
     * @param ctrl
     */
    public AjoutInterventionVue(Vehicule v, Controleur ctrl) {
        this.ctrl = ctrl;
        this.v = v;
        initComponents();
        initGUI();
        this.setVisible(true);
    }
    
    private void initGUI()
    {
        jCbTypeIntervention.setModel(new DefaultComboBoxModel(new String[]{"Mécanique", "Carrosserie"}));
        jCbPiece.setModel(new DefaultComboBoxModel(PieceMecanique.values()));
        jCbNatureIntervention.setModel(new DefaultComboBoxModel(TypeMecanique.values()));
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCbTypeIntervention = new javax.swing.JComboBox();
        jCbPiece = new javax.swing.JComboBox();
        jAnnuler = new javax.swing.JButton();
        jValider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCbNatureIntervention = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ajout d'une nouvelle intervention");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Type d'intervention :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Piece recquise :");

        jCbTypeIntervention.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbTypeIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTypeInterventionActionPerformed(evt);
            }
        });

        jCbPiece.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jAnnuler.setText("Annuler");
        jAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnulerActionPerformed(evt);
            }
        });

        jValider.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jValider.setText("Valider");
        jValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nature de l'intervention :");

        jCbNatureIntervention.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCbNatureIntervention, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCbTypeIntervention, 0, 150, Short.MAX_VALUE)))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jCbPiece, 0, 232, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jValider)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAnnuler)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbTypeIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbNatureIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnnuler)
                    .addComponent(jValider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbTypeInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTypeInterventionActionPerformed
        switch(jCbTypeIntervention.getSelectedItem().toString())
        {
            case "Mécanique":
                jCbPiece.setModel(new DefaultComboBoxModel(PieceMecanique.values()));
                jCbNatureIntervention.setModel(new DefaultComboBoxModel(TypeMecanique.values()));
                break;
            case "Carrosserie":
                jCbPiece.setModel(new DefaultComboBoxModel(PieceCarrosserie.values()));
                jCbNatureIntervention.setModel(new DefaultComboBoxModel(TypeCarrosserie.values()));
                break;
        }
    }//GEN-LAST:event_jCbTypeInterventionActionPerformed

    private void jAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jAnnulerActionPerformed

    private void jValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderActionPerformed
        switch(jCbTypeIntervention.getSelectedItem().toString())
        {
            case "Mécanique":
                v.ajouterIntervention(new InterventionMecanique((TypeMecanique) jCbNatureIntervention.getSelectedItem(),(PieceMecanique) jCbPiece.getSelectedItem()));
                this.dispose();
                break;
            case "Carrosserie":
                v.ajouterIntervention(new InterventionCarrosserie((TypeCarrosserie) jCbNatureIntervention.getSelectedItem(),(PieceCarrosserie) jCbPiece.getSelectedItem()));
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAnnuler;
    private javax.swing.JComboBox jCbNatureIntervention;
    private javax.swing.JComboBox jCbPiece;
    private javax.swing.JComboBox jCbTypeIntervention;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jValider;
    // End of variables declaration//GEN-END:variables
}
